export enum TypeNames {
  HANDLE_CHANGE_THEME_PROPERTYIES = 'HANDLE_CHANGE_THEME_PROPERTYIES',
  HANDLE_CHANGE_USER = 'HANDLE_CHANGE_USER',
  HANDLE_CHANGE_MESSAGE_MENU_PROPERTIES = 'HANDLE_CHANGE_MESSAGE_MENU_PROPERTIES',
  HANDLE_CHANGE_COMMENT_MENU_PROPERTIES = 'HANDLE_CHANGE_COMMENT_MENU_PROPERTIES',
    
}
